added lab1 main functionality
BohdanBodakva/my_flutter_application pull request #1
Opened 2024-02-25 22:06 UTC by BohdanBodakva

2024-02-25 22:15 UTC, DenysDoskochynskyi requested changes
Please add linter rules from my repo:)

2024-02-25 22:46 UTC, BohdanBodakva commented
Added linter and fixed all issues found by it. Now it all works well.

2024-02-26 12:38 UTC, DenysDoskochynskyi approved these changes
Just some minor comments, but everything is nice)

2024-02-26 12:38 UTC, DenysDoskochynskyi commented on lib/main.dart
>            children: <Widget>[
You can remove that <Widget> it's not necessary

2024-02-26 12:38 UTC, DenysDoskochynskyi commented on lib/main.dart
>    // This widget is the root of your application.
remove comments)

2024-02-26 12:38 UTC, DenysDoskochynskyi commented on lib/main.dart
>          useMaterial3: true,
No need to set that value(be default it's true)

2024-02-26 18:18 UTC, BohdanBodakva commented on lib/main.dart
>            children: <Widget>[
Fixed, thanks.

2024-02-26 18:18 UTC, BohdanBodakva commented on lib/main.dart
>    // This widget is the root of your application.
Fixed, thanks.

2024-02-26 18:18 UTC, BohdanBodakva commented on lib/main.dart
>          useMaterial3: true,
Fixed, thanks.

2024-03-02 11:29 UTC, merged